apply plugin: 'com.android.application'

android {
    namespace 'com.vrppoc'
    compileSdk 34

    defaultConfig {
        applicationId "com.vrppoc"
        minSdk 31
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
